name: CI Pipeline with unit and e2e tests

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t the-podcaster-app .

      - name: Run Docker container
        run: docker run --name the-podcaster-app-container -d the-podcaster-app

      - name: Run unit tests
        run: docker exec the-podcaster-app-container npm run test

      - name: Run Cypress tests
        run: docker exec the-podcaster-app-container npm run cypress:run

      - name: Stop and remove Docker container
        run: |
          docker stop the-podcaster-app-container
          docker rm the-podcaster-app-container
